title: KC Tsiolis
name: KC Tsiolis
email: kc.tsiolis@mail.utoronto.ca
description: >- # this means to ignore newlines until "baseurl:"
  PhD Student in Statistics at the University of Toronto and the Vector Institute
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"
locale: "en-CA"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
include: 
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock

logo: "files/bio_pic.jpg"
masthead_title: "KC Tsiolis"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "home"
      author_profile: true

author:
  name: "KC Tsiolis"
  avatar: "files/bio_pic.jpg"
  bio: "PhD Student in Statistics at the University of Toronto"
  location: "Toronto, Ontario, Canada"
  links:
    - label: "Google Scholar"
      icon: "fas fa-university"
      url: "https://scholar.google.ca/citations?user=UDxHX4sAAAAJ&hl=en&oi=ao"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/kctsiolis"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/kctsiolis"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/kctsiolis"




